CREATE TABLE  LTRKAP  (
       支払取引先コード                   CHAR(4)           NOT NULL,
       フラグ＿登録削除                   CHAR(1)           NOT NULL,
       ダミー００１                       CHAR(4)           NOT NULL,
       相手先名称                         VARCHAR2(56)      NOT NULL,
       口座名義人                         CHAR(30)          NOT NULL,
       銀行コード                         NUMBER(4,0)       NOT NULL,
       支店コード                         NUMBER(3,0)       NOT NULL,
       預金種目                           NUMBER(1,0)       NOT NULL,
       口座番号                           NUMBER(7,0)       NOT NULL,
       登録番号                           NUMBER(4,0)       NOT NULL,
       名宛人                             VARCHAR2(56)      NOT NULL,
       郵便番号＿親                       CHAR(3)           NOT NULL,
       郵便番号＿子                       CHAR(4)           NOT NULL,
       郵送先住所１                       VARCHAR2(34)      NOT NULL,
       郵送先住所２                       VARCHAR2(32)      NOT NULL,
       郵送先住所３                       VARCHAR2(32)      NOT NULL,
       郵送先名１                         VARCHAR2(28)      NOT NULL,
       郵送先名２                         VARCHAR2(28)      NOT NULL,
       休日対応区分                       CHAR(1)           NOT NULL,
       手数料有無                         CHAR(1)           NOT NULL,
       ダミー００２                       CHAR(56)          NOT NULL,
       共通情報                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_LTRKAP  PRIMARY KEY (
       支払取引先コード));
