CREATE TABLE ALM_FORM_0001M
(
    MON000                         CHAR(6),
    MON001                         CHAR(6),
    MON002                         CHAR(6),
    MON003                         CHAR(6),
    MON004                         CHAR(6),
    MON005                         CHAR(6),
    MON006                         CHAR(6),
    MON007                         CHAR(6),
    MON008                         CHAR(6),
    MON009                         CHAR(6),
    MON010                         CHAR(6),
    MON011                         CHAR(6),
    MON012                         CHAR(6)
)
/
