CREATE TABLE JOM_FORM_0009_H
(
    éxìXÇP                         VARCHAR2(20) NOT NULL,
    éxìXÇQ                         VARCHAR2(20) NOT NULL,
    éxìXÇR                         VARCHAR2(20) NOT NULL,
    éxìXÇS                         VARCHAR2(20) NOT NULL,
    éxìXÇT                         VARCHAR2(20) NOT NULL,
    éxìXÇU                         VARCHAR2(20) NOT NULL,
    éxìXÇV                         VARCHAR2(20) NOT NULL,
    éxìXÇW                         VARCHAR2(20) NOT NULL,
    éxìXÇX                         VARCHAR2(20) NOT NULL,
    éxìXÇPÇO                       VARCHAR2(20) NOT NULL,
    éxìXÇPÇP                       VARCHAR2(20) NOT NULL,
    éxìXÇPÇQ                       VARCHAR2(20) NOT NULL,
    éxìXÇPÇR                       VARCHAR2(20) NOT NULL,
    éxìXÇPÇS                       VARCHAR2(20) NOT NULL,
    çáåv                           VARCHAR2(20) NOT NULL
)
/
CREATE UNIQUE INDEX JOM_FORM_0009_H
ON JOM_FORM_0009_H
(éxìXÇP)
/
