CREATE TABLE  LTRKRN  (
       ä«óùÇmÇn                           CHAR(7)           NOT NULL,
       ìoò^çÌèú                           CHAR(1)           NOT NULL,
       É_É~Å[ÇOÇOÇP                       CHAR(4)           NOT NULL,
       ç≈êVé}î‘                           NUMBER(2,0)       NOT NULL,
       É_É~Å[ÇOÇOÇQ                       CHAR(51)          NOT NULL,
       ã§í èÓïÒ                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_LTRKRN  PRIMARY KEY (
       ä«óùÇmÇn));
