CREATE TABLE  LTRTUUH1  (
       ‚j‚d‚x‚P                           CHAR(2)           NOT NULL,
       ‚j‚d‚x‚Q                           CHAR(8)           NOT NULL,
       ˆê˜A”Ô†                           NUMBER(5,0)       NOT NULL,
       ƒ_ƒ~[‚O‚O‚P                       CHAR(50)          NOT NULL,
       ‹¤’Êî•ñ                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_LTRTUUH1  PRIMARY KEY (
       ‚j‚d‚x‚P,
       ‚j‚d‚x‚Q));
