CREATE TABLE MAN_UNMATTI
(
    ä«óùÇmÇn                       CHAR(6) NOT NULL,
    ó\îıÇP                         CHAR(2) NOT NULL,
    ã@éÌ                           CHAR(17) NOT NULL,
    ã@î‘                           CHAR(10) NOT NULL,
    ó\îıÇQ                         CHAR(36) NOT NULL,
    òAî‘                           NUMBER(3,0) NOT NULL,
    CONSTRAINT P_UNMATTI PRIMARY KEY (ä«óùÇmÇn, ã@î‘, òAî‘) USING INDEX
)
/
