CREATE TABLE KEI_WK_YOTEI3
(
    Œ_–ñ”Ô†                       CHAR(9) NOT NULL,
    ˜A”Ô                           NUMBER(3,0) NOT NULL,
    ’[––”Ô†                       VARCHAR2(16) NOT NULL,
    ‰ñ”‚P                         NUMBER(3,0),
    Žx•¥Šú“ú‚P                     CHAR(10),
    Žx•¥‹àŠz‚P                     NUMBER(13,0),
    Žx•¥Žc‚‚P                     NUMBER(13,0),
    ‰ñ”‚Q                         NUMBER(3,0),
    Žx•¥Šú“ú‚Q                     CHAR(10),
    Žx•¥‹àŠz‚Q                     NUMBER(13,0),
    Žx•¥Žc‚‚Q                     NUMBER(13,0),
    CONSTRAINT SYS_C0025860 PRIMARY KEY (Œ_–ñ”Ô†, ˜A”Ô, ’[––”Ô†) USING INDEX
)
/
