CREATE TABLE PAY_LBLPRT
(
    CTLNUM                         CHAR(9),
    DATNUM                         CHAR(4),
    BNKCOD                         CHAR(4),
    CNTNUM                         CHAR(9),
    ZIPLFT                         CHAR(7),
    ADRLF1                         CHAR(42),
    ADRLF2                         CHAR(42),
    ADRLF3                         CHAR(42),
    NAMLFT                         CHAR(42),
    DIVLFT                         CHAR(42),
    TYPLFT                         CHAR(1),
    ZIPRGT                         CHAR(7),
    ADRRG1                         CHAR(42),
    ADRRG2                         CHAR(42),
    ADRRG3                         CHAR(42),
    NAMRGT                         CHAR(42),
    DIVRGT                         CHAR(42),
    TYPRGT                         CHAR(1)
)
/
