CREATE TABLE ALM_ALMTR2
(
    DATTYP                         CHAR(1),
    CNTNUM                         CHAR(9),
    APRDAY                         CHAR(8),
    PLNDAY                         CHAR(8),
    PAYDAY                         CHAR(8),
    COLAMT                         NUMBER(13,0),
    CONTAX                         NUMBER(13,0),
    PREAMT                         NUMBER(13,0),
    SETAMT                         NUMBER(13,0),
    TIECOD                         CHAR(2),
    ERRFLG                         CHAR(5)
)
/
