CREATE TABLE ALM_ALMTR3
(
    DATTYP                         CHAR(1),
    CNTNUM                         CHAR(10),
    CNTDET                         CHAR(2),
    COLDAY                         CHAR(8),
    COLAMT                         NUMBER(13,0),
    CONTAX                         NUMBER(13,0),
    FINEND                         CHAR(8),
    ACCCOD                         CHAR(2),
    TIECOD                         CHAR(2),
    PAYCNT                         NUMBER(3,0),
    BASRAT                         NUMBER(10,8),
    ACTRAT                         NUMBER(10,8),
    PAYCYC                         NUMBER(2,0),
    FRZTRM                         NUMBER(3,0),
    BGNCNT                         NUMBER(1,0),
    CALTYP                         CHAR(1),
    ERRFLG                         CHAR(5)
)
/
