CREATE TABLE  LTRKKS  (
       Œ_–ñ”Ô†Q‚P                       CHAR(7)           NOT NULL,
       Œ_–ñ”Ô†Q‚Q                       CHAR(2)           NOT NULL,
       w“üæŽ¯•Ê”Ô†                     CHAR(2)           NOT NULL,
       Žx•¥æðŒŽ¯•Ê”Ô†                 NUMBER(2,0)       NOT NULL,
       •¨Œ‹àŠz                           NUMBER(13,0)      NOT NULL,
       Žd“üÁ”ïÅ                         NUMBER(13,0)      NOT NULL,
       [“–‘ŠŽE‹àŠz                       NUMBER(13,0)      NOT NULL,
       ‘O“n‹à                             NUMBER(13,0)      NOT NULL,
       Žx•¥‹àŠz                           NUMBER(13,0)      NOT NULL,
       Žx•¥ðŒƒR[ƒh                     NUMBER(2,0)       NOT NULL,
       Žx•¥ðŒ–¼                         VARCHAR2(40)      NOT NULL,
       Žx•¥•û–@                           NUMBER(2,0)       NOT NULL,
       Žx•¥—\’è“úQ“ú•tQ¢‹I             NUMBER(1,0)       NOT NULL,
       Žx•¥—\’è“úQ“ú•tQ”NŒŽ“ú           CHAR(6)           NOT NULL,
       ŽèŒ`Šú“úQ“ú•tQ¢‹I               NUMBER(1,0)       NOT NULL,
       ŽèŒ`Šú“úQ“ú•tQ”NŒŽ“ú             CHAR(6)           NOT NULL,
       Žx•¥ŽèŒ`•ªŠ„‹æ•ª                   NUMBER(1,0)       NOT NULL,
       Žx•¥ŽèŒ`“‡‹æ•ª                   NUMBER(1,0)       NOT NULL,
       [“–‘ŠŽEŠÖ˜AŒ_–ñ”Ô†               CHAR(9)           NOT NULL,
       Žx•¥“úUo“úQ“ú•tQ¢‹I           NUMBER(1,0)       NOT NULL,
       Žx•¥“úUo“úQ“ú•tQ”NŒŽ“ú         CHAR(6)           NOT NULL,
       Užî•ñQŒûÀ–¼                   VARCHAR2(56)      NOT NULL,
       Užî•ñQ‹âsƒR[ƒh               NUMBER(7,0)       NOT NULL,
       Užî•ñQ—a‹àŽí•Ê                 NUMBER(1,0)       NOT NULL,
       Užî•ñQŒûÀ”Ô†                 NUMBER(7,0)       NOT NULL,
       ŽèŒ`¬ØŽèî•ñQŽó“nƒR[ƒh         NUMBER(1,0)       NOT NULL,
       ŽèŒ`¬ØŽèî•ñQ—X‘—æ–¼           VARCHAR2(56)      NOT NULL,
       ŽèŒ`¬ØŽèî•ñQ—X•Ö”Ô†Qe       CHAR(3)           NOT NULL,
       ŽèŒ`¬ØŽèî•ñQ—X•Ö”Ô†QŽq       CHAR(4)           NOT NULL,
       ŽèŒ`¬ØŽèî•ñQ—X‘—æZŠ         VARCHAR2(98)      NOT NULL,
       Žx•¥Šm”FQ“ú•tQ¢‹I               NUMBER(1,0)       NOT NULL,
       Žx•¥Šm”FQ“ú•tQ”NŒŽ“ú             CHAR(6)           NOT NULL,
       Žx•¥Šm”FQ’S“–ŽÒƒR[ƒh             NUMBER(4,0)       NOT NULL,
       Žx•¥³”FQ“ú•tQ¢‹I               NUMBER(1,0)       NOT NULL,
       Žx•¥³”FQ“ú•tQ”NŒŽ“ú             CHAR(6)           NOT NULL,
       Žx•¥³”FQ’S“–ŽÒƒR[ƒh             NUMBER(4,0)       NOT NULL,
       Žx•¥³”FQ³”F‚m‚n                 CHAR(6)           NOT NULL,
       Žx•¥³”FQŽæÁ“úQ¢‹I             NUMBER(1,0)       NOT NULL,
       Žx•¥³”FQŽæÁ“úQ”NŒŽ“ú           CHAR(6)           NOT NULL,
       ‹x“ú”»’è‹æ•ª                       NUMBER(1,0)       NOT NULL,
       ƒ_ƒ~[‚O‚O‚P                       CHAR(33)          NOT NULL,
       ‹¤’Êî•ñ                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_LTRKKS  PRIMARY KEY (
       Œ_–ñ”Ô†Q‚P,
       Œ_–ñ”Ô†Q‚Q,
       w“üæŽ¯•Ê”Ô†,
       Žx•¥æðŒŽ¯•Ê”Ô†));
