CREATE TABLE  LTRTUUL000  (
       ÇjÇdÇxÇP                           CHAR(4)           NOT NULL,
       É_É~Å[ÇOÇOÇP                       CHAR(6)           NOT NULL,
       èàóùí î‘                           NUMBER(5,0)       NOT NULL,
       É_É~Å[ÇOÇOÇQ                       CHAR(50)          NOT NULL,
       ã§í èÓïÒ                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_LTRTUUL000  PRIMARY KEY (
       ÇjÇdÇxÇP,
       É_É~Å[ÇOÇOÇP));
