prompt PL/SQL Developer import file
prompt Created on 2004年10月22日 by ren_dali
set feedback off
set define off
prompt Dropping M01SAJ_TBL...
drop table M01SAJ_TBL cascade constraints;
prompt Creating M01SAJ_TBL...
create table M01SAJ_TBL
(
  レコード区分                   CHAR(1) not null,
  契約番号                       CHAR(15) not null,
  再リース回数                   NUMBER(2) not null,
  契約種類                       CHAR(3) not null,
  連番                           NUMBER(3) not null,
  請求区分                       CHAR(1) not null,
  解約売却取消区分               CHAR(1) not null,
  処理年月                       CHAR(6) not null,
  請求先取引先コード             CHAR(9) not null,
  顧客区分                       CHAR(2) not null,
  TASSコード                     CHAR(7) not null,
  貸倒年月日                     CHAR(8) not null,
  特定取引先区分                 CHAR(1) not null,
  最大督促回数                   CHAR(1) not null,
  契約日                         CHAR(8) not null,
  引渡年月日                     CHAR(8) not null,
  契約開始日                     CHAR(8) not null,
  契約終了日                     CHAR(8) not null,
  期間                           NUMBER(3) not null,
  契約区分                       CHAR(1) not null,
  リース開始区分                 CHAR(1) not null,
  担当部課コード                 CHAR(4) not null,
  担当者コード                   CHAR(8) not null,
  協調区分                       CHAR(1) not null,
  状態フラグ                     CHAR(1) not null,
  主契約区分                     CHAR(1) not null,
  遡及処理区分                   CHAR(1) not null,
  遡及処理年月                   CHAR(6) not null,
  成約年月                       CHAR(6) not null,
  成約取消年月                   CHAR(6) not null,
  検収処理年月                   CHAR(6) not null,
  検収取消日                     CHAR(8) not null,
  検収取消処理年月               CHAR(6) not null,
  最新回収期間                   NUMBER(3) not null,
  総回収回数                     NUMBER(3) not null,
  請求間隔                       NUMBER(2) not null,
  回収間隔                       NUMBER(2) not null,
  制度転登録年月                 CHAR(6) not null,
  制度転確定フラグ               CHAR(1) not null,
  回収サイト                     NUMBER(2) not null,
  回収方法                       CHAR(1) not null,
  再リース区分                   CHAR(1) not null,
  管理債権レベル                 CHAR(1) not null,
  前払フラグ                     CHAR(1) not null,
  督促回数                       NUMBER(1) not null,
  請求先コード                   CHAR(5) not null,
  契約先取引先コード             CHAR(9) not null,
  契約先コード                   CHAR(5) not null,
  支払取引先コード               CHAR(9) not null,
  支払先コード                   CHAR(5) not null,
  雑費販促費                     NUMBER(13) not null,
  最新月額料金                   NUMBER(13) not null,
  最新消費率                     NUMBER(9,7) not null,
  最新消費税額                   NUMBER(13) not null,
  当初契約総額                   NUMBER(13) not null,
  当初消費税総額                 NUMBER(13) not null,
  最新契約総額                   NUMBER(13) not null,
  最新消費税総額                 NUMBER(13) not null,
  保守無償期間                   NUMBER(3) not null,
  回収額                         NUMBER(13) not null,
  消費税回収額                   NUMBER(13) not null,
  最新回収日                     CHAR(8) not null,
  割賦原価総額                   NUMBER(13) not null,
  割賦利益総額                   NUMBER(13) not null,
  当初取得価額                   NUMBER(13) not null,
  満了フラグ                     CHAR(1) not null,
  満了日                         CHAR(8) not null,
  資産種類                       CHAR(5) not null,
  合算先契約種類                 CHAR(3) not null,
  貸付利率                       NUMBER(9,7) not null,
  再リース手数料                 NUMBER(13) not null,
  委託保守区分                   CHAR(1) not null,
  委託保守相当月額               NUMBER(13) not null,
  制度転支払月額                 NUMBER(13) not null,
  前払月数                       NUMBER(3) not null,
  その他契約種類区分             CHAR(1) not null,
  契約種類区分                   CHAR(1) not null,
  契約種類内部コード             CHAR(2) not null,
  支払利息                       NUMBER(13) not null,
  原価調整額                     NUMBER(13) not null,
  固定資産税                     NUMBER(13) not null,
  年利回り                       NUMBER(5,3) not null,
  運用利回り                     NUMBER(5,3) not null,
  粗利益額                       NUMBER(13) not null,
  粗利益額＿表                   NUMBER(13) not null,
  粗利益額＿裏                   NUMBER(13) not null,
  規定損害金基本額               NUMBER(13) not null,
  信用保険料                     NUMBER(13) not null,
  動産保険料                     NUMBER(13) not null,
  保守料                         NUMBER(13) not null,
  その他雑費                     NUMBER(13) not null,
  手数料                         NUMBER(13) not null,
  手形受取日                     CHAR(8) not null,
  手形枚数                       NUMBER(3) not null,
  格付区分                       CHAR(2) not null,
  取得価額                       NUMBER(13) not null,
  自社分月額料金                 NUMBER(13) not null,
  自社分月額消費税               NUMBER(13) not null,
  自社分契約総額                 NUMBER(13) not null,
  自社分消費税総額               NUMBER(13) not null,
  他社購入額                     NUMBER(13) not null,
  残価設定額                     NUMBER(13) not null,
  他社残価設定額                 NUMBER(13) not null,
  他社回収額                     NUMBER(13) not null,
  他社回収額消費税               NUMBER(13) not null,
  他社割賦原価総額               NUMBER(13) not null,
  他社割賦利益総額               NUMBER(13) not null,
  解約フラグ                     CHAR(1) not null,
  解約日                         CHAR(8) not null,
  解約回数                       NUMBER(3) not null,
  解約区分                       CHAR(1) not null,
  解約理由                       CHAR(2) not null,
  解約処理年月                   CHAR(6) not null,
  取消区分                       CHAR(1) not null,
  解約取消処理年月               CHAR(6) not null,
  解約年月                       CHAR(6) not null,
  解約月数                       NUMBER(3) not null,
  前月債権総額                   NUMBER(13) not null,
  前月売上総額                   NUMBER(13) not null,
  前月売上総額他社               NUMBER(13) not null,
  前月消費税総額                 NUMBER(13) not null,
  前月消費税総額他社             NUMBER(13) not null,
  売上総額                       NUMBER(13) not null,
  売上総額他社                   NUMBER(13) not null,
  売上消費税総額                 NUMBER(13) not null,
  売上消費税総額他社             NUMBER(13) not null,
  前期末未実現残高               NUMBER(13) not null,
  前期末未実現残高他社           NUMBER(13) not null,
  前期迄売上額累計               NUMBER(13) not null,
  前期迄売上額累計他社           NUMBER(13) not null,
  前期迄消費税額累計             NUMBER(13) not null,
  前期迄消費税額累計他社         NUMBER(13) not null,
  当月売上額                     NUMBER(13) not null,
  当月売上額２                   NUMBER(13) not null,
  当月売上額他社                 NUMBER(13) not null,
  当月消費税相当額               NUMBER(13) not null,
  当月消費税相当額２             NUMBER(13) not null,
  当月消費税相当額他社           NUMBER(13) not null,
  当月消費税率                   NUMBER(9,7) not null,
  当月消費税率２                 NUMBER(9,7) not null,
  当月消費税率他社               NUMBER(9,7) not null,
  当月迄売上額累計               NUMBER(13) not null,
  当月迄売上額累計他社           NUMBER(13) not null,
  当月迄消費税額累計             NUMBER(13) not null,
  当月迄消費税額累計他社         NUMBER(13) not null,
  当期売上額累計                 NUMBER(13) not null,
  当期売上額累計他社             NUMBER(13) not null,
  当月末未実現残高               NUMBER(13) not null,
  当月末未実現残高他社           NUMBER(13) not null,
  当月売上増加額                 NUMBER(13) not null,
  当月売上増加額他社             NUMBER(13) not null,
  当月消費税増加額               NUMBER(13) not null,
  当月消費税増加額他社           NUMBER(13) not null,
  当月売上減少額                 NUMBER(13) not null,
  当月売上減少額他社             NUMBER(13) not null,
  当月消費税減少額               NUMBER(13) not null,
  当月消費税減少額他社           NUMBER(13) not null,
  当月遡及分増加自売上年月       CHAR(6) not null,
  当月遡及分増加至売上年月       CHAR(6) not null,
  当月遡及分売上増加額           NUMBER(13) not null,
  当月遡及分売上増加額２         NUMBER(13) not null,
  当月遡及分売上増加額他社       NUMBER(13) not null,
  当月遡及分消費税増加額         NUMBER(13) not null,
  当月遡及分消費税増加額２       NUMBER(13) not null,
  当月遡及分消費税増加額他社     NUMBER(13) not null,
  当月遡及分減少自売上年月       CHAR(6) not null,
  当月遡及分減少至売上年月       CHAR(6) not null,
  当月遡及分売上減少額           NUMBER(13) not null,
  当月遡及分売上減少額２         NUMBER(13) not null,
  当月遡及分売上減少額他社       NUMBER(13) not null,
  当月遡及分消費税減少額         NUMBER(13) not null,
  当月遡及分消費税減少額２       NUMBER(13) not null,
  当月遡及分消費税減少額他社     NUMBER(13) not null,
  当月遡及分消費税率             NUMBER(9,7) not null,
  当月遡及分消費税率２           NUMBER(9,7) not null,
  前月売上額                     NUMBER(13) not null,
  前月売上額２                   NUMBER(13) not null,
  前月売上額他社                 NUMBER(13) not null,
  前月消費税相当額               NUMBER(13) not null,
  前月消費税相当額２             NUMBER(13) not null,
  前月消費税相当額他社           NUMBER(13) not null,
  前月迄売上額累計               NUMBER(13) not null,
  前月迄売上額累計他社           NUMBER(13) not null,
  前月迄消費税額累計             NUMBER(13) not null,
  前月迄消費税額累計他社         NUMBER(13) not null,
  前期末元本残高                 NUMBER(13) not null,
  前期末利息残高                 NUMBER(13) not null,
  前月迄元本回収額累計           NUMBER(13) not null,
  前月迄利息回収額累計           NUMBER(13) not null,
  前月末元本残高                 NUMBER(13) not null,
  前月末利息残高                 NUMBER(13) not null,
  新規増加分元本額               NUMBER(13) not null,
  新規増加分利息額               NUMBER(13) not null,
  当月元本入金額                 NUMBER(13) not null,
  当月利息入金額                 NUMBER(13) not null,
  当月末元本残高                 NUMBER(13) not null,
  当月末利息残高                 NUMBER(13) not null,
  当月迄元本収入予定額累計       NUMBER(13) not null,
  当月迄利息収入予定額累計       NUMBER(13) not null,
  当月迄元本回収額累計           NUMBER(13) not null,
  当月迄利息回収額累計           NUMBER(13) not null,
  当月迄元本回収額累計他社       NUMBER(13) not null,
  当月迄利息回収額累計他社       NUMBER(13) not null,
  当月回収予定額                 NUMBER(13) not null,
  元本未経過リース料             NUMBER(13) not null,
  利息未経過リース料             NUMBER(13) not null,
  元本未収リース料               NUMBER(13) not null,
  利息未収リース料               NUMBER(13) not null,
  当月前受リース料入金額         NUMBER(13) not null,
  当月迄前受リース料入金額       NUMBER(13) not null,
  当月仮受金振替金額             NUMBER(13) not null,
  当月仮受金振替利息             NUMBER(13) not null,
  元本前受金                     NUMBER(13) not null,
  利息前受金                     NUMBER(13) not null,
  仮受金                         NUMBER(13) not null,
  貸倒損失額                     NUMBER(13) not null,
  現在簿価                       NUMBER(13) not null,
  耐用年数                       NUMBER(2) not null,
  保険料率                       NUMBER(2) not null,
  拘束期間後当月レンタル料       NUMBER(13) not null,
  当月売上対象フラグ             CHAR(1) not null,
  新契約番号                     CHAR(15) not null,
  当月売上調整フラグ             CHAR(1) not null,
  当月条件変更フラグ             CHAR(1) not null,
  営業概要契約抽出フラグ         CHAR(1) not null,
  営業概要検収抽出フラグ         CHAR(1) not null,
  営業所区分                     CHAR(1) not null,
  契約内容契約件名               VARCHAR2(40) not null,
  債権契約件名                   VARCHAR2(40) not null,
  成約日                         CHAR(8) not null,
  社内金利                       NUMBER(5,3) not null,
  年粗利率                       NUMBER(5,3) not null,
  販売促進費                     NUMBER(13) not null,
  雑費                           NUMBER(13) not null,
  最終回収予定日                 CHAR(8) not null,
  会計部門コード                 CHAR(2) not null,
  満了売却フラグ                 CHAR(1) not null,
  債権譲渡支払額                 NUMBER(13) not null,
  仕訳フラグ＿売上               CHAR(1) not null,
  仕訳フラグ＿検収               CHAR(1) not null,
  再リース取消エントリ日         CHAR(8) not null,
  消費税区分                     CHAR(2) not null,
  当初他社購入額                 NUMBER(13) not null,
  他社最新契約総額               NUMBER(13) not null,
  他社最新消費税総額             NUMBER(13) not null,
  他社契約総額                   NUMBER(13) not null,
  成約取消エントリ日             CHAR(8) not null,
  売廃フラグ                     CHAR(1) not null,
  再リース処理年月               CHAR(6) not null,
  再リース自動継続区分           CHAR(1) not null,
  再リース申請書有無区分         CHAR(1) not null,
  再リース申請フラグ             CHAR(1) not null,
  解約申請フラグ                 CHAR(1) not null,
  自動請求区分                   CHAR(1) not null,
  前月割賦原価総額               NUMBER(13) not null,
  前月他社割賦原価総額           NUMBER(13) not null,
  頭金区分                       CHAR(1) not null,
  コンスーマ法人区分             CHAR(1) not null,
  申請連番                       NUMBER(4) not null,
  未収残高対象外フラグ           CHAR(1) not null,
  前月状態フラグ                 CHAR(1) not null,
  入金回数                       NUMBER(3) not null,
  実現回数                       NUMBER(3) not null,
  当月遡及分増加自売上年月２     CHAR(6) not null,
  当月遡及分増加至売上年月２     CHAR(6) not null,
  当月遡及分減少自売上年月２     CHAR(6) not null,
  当月遡及分減少至売上年月２     CHAR(6) not null,
  初回回収予定日                 CHAR(8) not null,
  前月迄元本収入予定額累計       NUMBER(13) not null,
  前月迄利息収入予定額累計       NUMBER(13) not null,
  最新対外契約番号               CHAR(15) not null,
  割賦頭金                       NUMBER(13) not null,
  割賦頭金他社                   NUMBER(13) not null,
  割賦頭金消費税                 NUMBER(13) not null,
  割賦頭金消費税他社             NUMBER(13) not null,
  前月他社最新契約総額           NUMBER(13) not null,
  前月他社最新消費税総額         NUMBER(13) not null,
  前期末元本残高他社             NUMBER(13) not null,
  前期末利息残高他社             NUMBER(13) not null,
  前月迄元本回収額累計他社       NUMBER(13) not null,
  前月迄利息回収額累計他社       NUMBER(13) not null,
  前月末元本残高他社             NUMBER(13) not null,
  前月末利息残高他社             NUMBER(13) not null,
  新規増加分元本額他社           NUMBER(13) not null,
  新規増加分利息額他社           NUMBER(13) not null,
  当月元本入金額他社             NUMBER(13) not null,
  当月利息入金額他社             NUMBER(13) not null,
  当月末元本残高他社             NUMBER(13) not null,
  当月末利息残高他社             NUMBER(13) not null,
  当月迄元本収入予定額累計他社   NUMBER(13) not null,
  当月迄利息収入予定額累計他社   NUMBER(13) not null,
  当月回収予定額他社             NUMBER(13) not null,
  元本未経過リース料他社         NUMBER(13) not null,
  利息未経過リース料他社         NUMBER(13) not null,
  元本未収リース料他社           NUMBER(13) not null,
  利息未収リース料他社           NUMBER(13) not null,
  当月前受リース料入金額他社     NUMBER(13) not null,
  当月迄前受リース料入金額他社   NUMBER(13) not null,
  元本前受金他社                 NUMBER(13) not null,
  利息前受金他社                 NUMBER(13) not null,
  検収エントリ日                 CHAR(8) not null,
  前月売上総額再リース           NUMBER(13) not null,
  売上総額再リース               NUMBER(13) not null,
  前期迄売上額累計再リース       NUMBER(13) not null,
  当月売上額再リース             NUMBER(13) not null,
  当月迄売上額累計再リース       NUMBER(13) not null,
  当期売上額累計再リース         NUMBER(13) not null,
  当月遡及分売上増加額再リース   NUMBER(13) not null,
  当月遡及分売上減少額再リース   NUMBER(13) not null,
  前月迄売上額累計再リース       NUMBER(13) not null,
  今回再リース料金区分           CHAR(1) not null,
  当月末未実現残高再リース       NUMBER(13) not null,
  前期末未実現残高再リース       NUMBER(13) not null,
  前月債権消費税総額             NUMBER(13) not null,
  当月仮受金振替金額他社         NUMBER(13) not null,
  当月仮受金振替利息他社         NUMBER(13) not null,
  仮受金他社                     NUMBER(13) not null,
  貸倒損失額利息相当額           NUMBER(13) not null,
  経理用主契約区分               CHAR(1) not null,
  違約金分割回収売上額           NUMBER(13) not null,
  違約金分割回収売上額消費税     NUMBER(13) not null,
  検収取消エントリ日             CHAR(8) not null,
  当月前受金入金額               NUMBER(13) not null,
  当月前受金入金額他社           NUMBER(13) not null,
  当月末前受金残高               NUMBER(13) not null,
  当月末前受金残高他社           NUMBER(13) not null,
  検収エントリ処理年月           CHAR(6) default '000000' not null,
  台帳＿当月入金回収額           NUMBER(13) default 0 not null,
  台帳＿当月入金回収額他社       NUMBER(13) default 0 not null,
  台帳＿当月入金前受額           NUMBER(13) default 0 not null,
  台帳＿当月入金前受額他社       NUMBER(13) default 0 not null,
  担保区分                       CHAR(1) default '0' not null,
  頭金回収サイト                 NUMBER(2) default 0 not null,
  頭金計上年月日                 CHAR(8) default '0' not null,
  契約内容＿解約処理年月         CHAR(6) not null,
  債権＿解約処理年月             CHAR(6) not null,
  解約履歴＿貸倒損失額           NUMBER(13) not null,
  解約履歴＿貸倒損失額利益相当額 NUMBER(13) not null,
  割賦頭金消費税率               NUMBER(9,7) not null,
  当月前受リース料消化額         NUMBER(13) not null,
  当月前受金消化額他社           NUMBER(13) not null,
  当月末前受リース料残高他社     NUMBER(13) not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 3712K
    minextents 1
    maxextents unlimited
  );
comment on table M01SAJ_TBL
  is '債権情報(一般)';
alter table M01SAJ_TBL
  add constraint PK_M01SAJ_TBL primary key (レコード区分,契約番号,再リース回数,契約種類,連番,請求区分,解約売却取消区分,申請連番)
  using index 
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 128K
    minextents 1
    maxextents unlimited
  );

prompt Disabling triggers for M01SAJ_TBL...
alter table M01SAJ_TBL disable all triggers;
prompt Loading M01SAJ_TBL...
prompt Table is empty
prompt Enabling triggers for M01SAJ_TBL...
alter table M01SAJ_TBL enable all triggers;
set feedback on
set define on
prompt Done.
