CREATE TABLE D02SQS_TBL(
    取引先コード                CHAR(9)         NOT NULL,
    請求先コード                CHAR(5)         NOT NULL,
    請求先名称                  VARCHAR2(80)    NOT NULL,
    部門名称                    VARCHAR2(60)    NOT NULL,
    担当者名称                  VARCHAR2(20)    NOT NULL,
    請求書表示                  CHAR(1)         NOT NULL,
    振込人名                    VARCHAR2(40)    NOT NULL,
    郵便番号                    CHAR(7)         NOT NULL,
    納付先コード                CHAR(11)        NOT NULL,
    住所２                      VARCHAR2(60)    NOT NULL,
    住所３                      VARCHAR2(60)    NOT NULL,
    電話番号                    CHAR(15)        NOT NULL,
    一括入金コード              CHAR(5)         NOT NULL,
    送付先名称                  VARCHAR2(60)    NOT NULL,
    送付先部門                  VARCHAR2(60)    NOT NULL,
    送付先担当者                VARCHAR2(20)    NOT NULL,
    送付先カナ名称              VARCHAR2(40)    NOT NULL,
    送付先郵便番号              CHAR(7)         NOT NULL,
    送付先市町村コード          CHAR(11)        NOT NULL,
    送付先住所２                VARCHAR2(60)    NOT NULL,
    送付先住所３                VARCHAR2(60)    NOT NULL,
    送付先電話番号              CHAR(15)        NOT NULL,
    自動マッチング対象外区分    CHAR(1)         NOT NULL,
    回収サイト                  NUMBER(2, 0)    NOT NULL,
    回収日                      CHAR(2)         NOT NULL,
    回収方法                    CHAR(1)         NOT NULL,
    回収間隔                    NUMBER(2, 0)    NOT NULL,
    請求サイト                  NUMBER(2, 0)    NOT NULL,
    請求締日                    CHAR(2)         NOT NULL,
    請求間隔                    NUMBER(2, 0)    NOT NULL,
    請求基準月                  NUMBER(2, 0)    NOT NULL,
    作成通数                    NUMBER(2, 0)    NOT NULL,
    作成単位                    CHAR(1)         NOT NULL,
    請求書作成区分              CHAR(1)         NOT NULL,
    請求指定様式区分            CHAR(1)         NOT NULL,
    送付区分                    CHAR(1)         NOT NULL,
    受取側金融機関コード        CHAR(4)         NOT NULL,
    受取側支店コード            CHAR(3)         NOT NULL,
    受取側口座種類              CHAR(1)         NOT NULL,
    受取側口座番号              CHAR(10)        NOT NULL,
    口振銀行コード              CHAR(4)         NOT NULL,
    口振支店コード              CHAR(3)         NOT NULL,
    口振口座種類                CHAR(1)         NOT NULL,
    口振口座番号                CHAR(10)        NOT NULL,
    口振名義人                  VARCHAR2(30)    NOT NULL,
    請求宛名印刷                CHAR(1)         NOT NULL,
    請求日付印刷                CHAR(1)         NOT NULL,
    回収期限印刷                CHAR(1)         NOT NULL,
    使用月印刷                  CHAR(1)         NOT NULL,
    内訳印刷                    CHAR(1)         NOT NULL,
    請求番号印刷                CHAR(1)         NOT NULL,
    摘要欄印刷                  CHAR(1)         NOT NULL,
    摘要欄                      VARCHAR2(60)    NOT NULL,
    備考欄印刷                  CHAR(1)         NOT NULL,
    口振ご案内書作成区分        CHAR(1)         NOT NULL,
    集約区分                    CHAR(1)         NOT NULL,
    更新日時                    CHAR(16)        NOT NULL,
    更新者                      CHAR(8)         NOT NULL,
    送付先コード                CHAR(3)         NOT NULL,
    仮想口座連番                NUMBER(3, 0)    NOT NULL,
    顧客使用不可フラグ          CHAR(1)         NOT NULL,
    コメント欄                  VARCHAR2(60)    NOT NULL,
    入力担当者コード            CHAR(8)         NOT NULL,
    部門カナ名称                VARCHAR2(30)    NOT NULL,
    契約先コード                CHAR(5)         NOT NULL,
    共有フラグ                  CHAR(1)         NOT NULL,
    住所１                      VARCHAR2(60)    NOT NULL,
    住所カナ名称                VARCHAR2(60)    NOT NULL,
    ＦＡＸ番号                  CHAR(15)        NOT NULL,
    振替銀行コード              CHAR(4)         NOT NULL,
    自振引落日                  CHAR(2)         NOT NULL,
    受取側口座コード            CHAR(2)         NOT NULL,
    振込手数料負担区分          CHAR(1)         NOT NULL,
    現担当者                    CHAR(8)         NOT NULL,
    主担当部課コード            CHAR(4)         NOT NULL,
    登録年月日                  CHAR(8)         NOT NULL,
    登録時間                    CHAR(8)         NOT NULL,
    登録担当者                  CHAR(8)         NOT NULL,
    更新年月日                  CHAR(8)         NOT NULL,
    更新時間                    CHAR(8)         NOT NULL,
    旧請求先コード              CHAR(8)         NOT NULL,
    口座引落依頼書受領日        CHAR(8)         NOT NULL,
    口座引落開始日              CHAR(8)         NOT NULL,
    CONSTRAINT PK18_2 PRIMARY KEY (取引先コード, 請求先コード)
) 
;
