CREATE TABLE ALM_FORM_0001Y
(
    YER000                         CHAR(4),
    YER001                         CHAR(4),
    YER002                         CHAR(4),
    YER003                         CHAR(4),
    YER004                         CHAR(4),
    YER005                         CHAR(4),
    YER006                         CHAR(4),
    YER007                         CHAR(4),
    YER008                         CHAR(4),
    YER009                         CHAR(4),
    YER010                         CHAR(4),
    YER011                         CHAR(4),
    YER012                         CHAR(4)
)
/
