CREATE TABLE ALM_ALMTRN
(
    ASTLIA                         CHAR(1),
    ALMDET                         CHAR(2),
    FIXFLT                         CHAR(1),
    ACCCOD                         CHAR(5),
    DUECOD                         CHAR(2),
    MONCNT                         NUMBER(3,0),
    BASYER                         CHAR(4),
    BASMON                         CHAR(2),
    COLAMT                         NUMBER(13,0),
    COLRAT                         NUMBER(4,2),
    BALCAP                         NUMBER(13,0),
    AVEBAL                         NUMBER(13,0),
    AVEINT                         NUMBER(13,0),
    AVERAT                         NUMBER(4,2),
    DIVCOD                         CHAR(1),
    GAPFLG                         CHAR(1),
    ACCTYP                         CHAR(1),
    COLINT                         NUMBER(13,0),
    BALAST                         NUMBER(13,0),
    BALPRE                         NUMBER(13,0),
    WKRAT1                         NUMBER(4,2),
    WKRAT2                         NUMBER(4,2),
    WKAMT1                         NUMBER(13,0),
    WKAMT2                         NUMBER(13,0),
    ERRFLG                         CHAR(5)
)
/
