CREATE TABLE  CPDTUUH2  (
       ‚j‚d‚x‚P                           CHAR(2)           NOT NULL,
       ‚j‚d‚x‚Q                           CHAR(8)           NOT NULL,
       ˆê˜A”Ô†                           NUMBER(3,0)       NOT NULL,
       ƒ_ƒ~[‚O‚O‚P                       CHAR(52)          NOT NULL,
       ‹¤’Êî•ñ                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_CPDTUUH2  PRIMARY KEY (
       ‚j‚d‚x‚P,
       ‚j‚d‚x‚Q));
