CREATE TABLE  LTRTUU  (
       éñã∆èä                             CHAR(4)           NOT NULL,
       É_É~Å[ÇOÇOÇP                       CHAR(6)           NOT NULL,
       èàóùí î‘                           CHAR(5)           NOT NULL,
       É_É~Å[ÇOÇOÇQ                       CHAR(50)          NOT NULL,
       ã§í èÓïÒ                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_LTRTUU  PRIMARY KEY (
       éñã∆èä,
       É_É~Å[ÇOÇOÇP));
