CREATE TABLE NYU_AUTOAPPL
(
    OPEDAY                         CHAR(8) NOT NULL,
    BNKCOD                         CHAR(4) NOT NULL,
    BNKKNJ                         CHAR(16) NOT NULL,
    FLPCNT                         CHAR(1) NOT NULL,
    TOTCNT                         NUMBER(5,0) NOT NULL,
    TOTAMT                         NUMBER(10,0) NOT NULL,
    PAYDAY                         CHAR(4) NOT NULL
)
/
