CREATE TABLE SSF_LPWK_CHOHYO
(
    í[ññî‘çÜ                       VARCHAR2(16) NOT NULL,
    òAî‘                           NUMBER(4,0),
    í†ï[ÇP                         NUMBER(1,0),
    í†ï[ÇQ                         NUMBER(1,0),
    í†ï[ÇR                         NUMBER(1,0),
    í†ï[ÇS                         NUMBER(1,0),
    í†ï[ÇT                         NUMBER(1,0),
    í†ï[ÇU                         NUMBER(1,0),
    í†ï[ÇV                         NUMBER(1,0),
    í†ï[ÇW                         NUMBER(1,0),
    í†ï[ÇX                         NUMBER(1,0),
    í†ï[ÇPÇO                       NUMBER(1,0),
    í†ï[ÇPÇP                       NUMBER(1,0),
    í†ï[ÇPÇQ                       NUMBER(1,0),
    í†ï[ÇPÇR                       NUMBER(1,0),
    í†ï[ÇPÇS                       NUMBER(1,0),
    í†ï[ÇPÇT                       NUMBER(1,0),
    í†ï[ÇPÇU                       NUMBER(1,0),
    í†ï[ÇPÇV                       NUMBER(1,0),
    í†ï[ÇPÇW                       NUMBER(1,0),
    í†ï[ÇPÇX                       NUMBER(1,0),
    í†ï[ÇQÇO                       NUMBER(1,0),
    éxï•äJénì˙                     CHAR(8),
    ëÊÇQâÒñ⁄à»ç~éxï•äJénì˙         CHAR(8),
    CONSTRAINT SSF_LPWK_CHOHYO PRIMARY KEY (í[ññî‘çÜ) USING INDEX
)
/
