[Profile]
ID=WS
Version=6
[Telnet3270]
HostName=127.0.0.1
HostPortNumber=3270
Security=N
[Communication]
Link=telnet3270
[3270]
QueryReplyMode=Auto
HostCodePage=037-U
[Keyboard]
CuaKeyboard=1
Language=United-States
DefaultKeyboard=$$BLANK$$
[LT]
IgnoreWCCStartPrint=Y
UndefinedCode=Y
UndefinedDBCSChar=Y