CREATE TABLE D415UTM_TBL(
    契約番号                CHAR(10)         NOT NULL,
    明細番号                NUMBER(3, 0)     NOT NULL,
    取引先コード            CHAR(9)          NOT NULL,
    契約先コード            CHAR(5)          NOT NULL,
    額面金額                NUMBER(13, 0)    NOT NULL,
    手形期日                CHAR(8)          NOT NULL,
    利息期日                CHAR(8)          NOT NULL,
    日数                    NUMBER(3, 0)     NOT NULL,
    割引率                  NUMBER(10, 8)    NOT NULL,
    割引料                  NUMBER(13, 0)    NOT NULL,
    取立手数料等            NUMBER(13, 0)    NOT NULL,
    取立手数料等消費税額    NUMBER(13, 0)    NOT NULL,
    買取代金額              NUMBER(13, 0)    NOT NULL,
    社内金利区分            CHAR(1)          NOT NULL,
    社内金利                NUMBER(10, 8)    NOT NULL,
    実質年率                NUMBER(10, 8)    NOT NULL,
    粗利                    NUMBER(13, 0)    NOT NULL,
    手形番号                CHAR(10)         NOT NULL,
    手形種類                CHAR(1)          NOT NULL,
    支払銀行コード          CHAR(4)          NOT NULL,
    支払支店コード          CHAR(3)          NOT NULL,
    請求取引先コード        CHAR(9)          NOT NULL,
    請求先コード            CHAR(5)          NOT NULL,
    社内金利_一般           NUMBER(10, 8)    NOT NULL,
    粗利_一般               NUMBER(13, 0)    NOT NULL,
    期限前決裁日            CHAR(8)          NOT NULL,
    流動化先                CHAR(10)         NOT NULL,
    債権流動化先区分        CHAR(1)          NOT NULL,
    更新年月日              CHAR(8)          NOT NULL,
    更新時間                CHAR(8)          NOT NULL,
    更新者                  CHAR(8)          NOT NULL,
    入力担当者コード        CHAR(8)          NOT NULL,
    登録年月日              CHAR(8)          NOT NULL,
    登録時間                CHAR(8)          NOT NULL,
    登録担当者              CHAR(8)          NOT NULL,
    CONSTRAINT PK16_4 PRIMARY KEY (契約番号, 明細番号)
) 
;
