CREATE TABLE JYO_CHKTMP
(
    ダミー１                       VARCHAR2(20),
    データ区分                     CHAR(1),
    資産番号                       CHAR(9),
    ダミー２                       VARCHAR2(31),
    ダミー３                       CHAR(8),
    資産種類                       CHAR(1),
    資産コード                     CHAR(6),
    耐用年数                       CHAR(2),
    償却率                         CHAR(3),
    ダミー４                       VARCHAR2(19)
)
/
