CREATE TABLE KEI_WK_YOTEI1
(
    Œ_–ñ”Ô†                       CHAR(9) NOT NULL,
    ’[––”Ô†                       VARCHAR2(16) NOT NULL,
    Žæˆøæ“s“¹•{Œ§–¼               CHAR(22),
    ŽæˆøæZŠ‚P                   CHAR(40),
    ŽæˆøæZŠ‚Q                   CHAR(40),
    Žæˆøæ–¼                       CHAR(60),
    “Œ‹âŽ–‹ÆŠ–¼                   CHAR(20),
    “Œ‹âŽ–‹ÆŠZŠ                 CHAR(90),
    “Œ‹â’S“–ŽÒ–¼                   CHAR(20),
    “Œ‹âŽ–‹ÆŠ“d˜b                 CHAR(15),
    CONSTRAINT SYS_C0025853 PRIMARY KEY (Œ_–ñ”Ô†, ’[––”Ô†) USING INDEX
)
/
