CREATE TABLE  LTRTUUT2  (
       ‚j‚d‚x‚P                           CHAR(2)           NOT NULL,
       ‚j‚d‚x‚Q                           CHAR(8)           NOT NULL,
       ŒŽ                                 NUMBER(2,0)       NOT NULL,
       “ú                                 NUMBER(2,0)       NOT NULL,
       ˆê˜A”Ô†Ì”Ô—p                     NUMBER(5,0)       NOT NULL,
       ƒ_ƒ~[‚O‚O‚P                       CHAR(46)          NOT NULL,
       ‹¤’Êî•ñ                           CHAR(35)          NOT NULL,
CONSTRAINT  PK_LTRTUUT2  PRIMARY KEY (
       ‚j‚d‚x‚P,
       ‚j‚d‚x‚Q));
