CREATE TABLE SIN_CHOHYO_WK
(
    ’[––‚h‚c                       CHAR(8) NOT NULL,
    ’ •[‚P                         CHAR(1) NOT NULL,
    ’ •[‚Q                         CHAR(1) NOT NULL,
    ’ •[‚R                         CHAR(1) NOT NULL,
    ’ •[‚S                         CHAR(1) NOT NULL,
    ’ •[‚T                         CHAR(1) NOT NULL,
    ’ •[‚U                         CHAR(1) NOT NULL,
    ’ •[‚V                         CHAR(1) NOT NULL,
    ’ •[‚W                         CHAR(1) NOT NULL,
    ’ •[‚X                         CHAR(1) NOT NULL,
    ’ •[‚P‚O                       CHAR(1) NOT NULL,
    CONSTRAINT SYS_C0028615 PRIMARY KEY (’[––‚h‚c) USING INDEX
)
/
